development:
    consumer_key = "PVGke8Dn7VgmjJ7GBnKw"
    consumer_secret = "jCKFTliN9bwEcVd5VEfFRqIEddQIgfkH5jAgfcJRmo"
  oauth_token = "623636422-iLbG9AnyNIYH5xWb641ZWeZKjQaT1ETSd2pXIY3Y"
  oauth_token_secret = "zaM00kSIcQFGjZ4Nlf5ws2CGzZmgw2y6SNbRP3uJUs"
test:
    consumer_key = "PVGke8Dn7VgmjJ7GBnKw"
    consumer_secret = "jCKFTliN9bwEcVd5VEfFRqIEddQIgfkH5jAgfcJRmo"
    oauth_token = "623636422-iLbG9AnyNIYH5xWb641ZWeZKjQaT1ETSd2pXIY3Y"
    oauth_token_secret = "zaM00kSIcQFGjZ4Nlf5ws2CGzZmgw2y6SNbRP3uJUs"
production:
    consumer_key = "PVGke8Dn7VgmjJ7GBnKw"
    consumer_secret = "jCKFTliN9bwEcVd5VEfFRqIEddQIgfkH5jAgfcJRmo"
  oauth_token = "623636422-iLbG9AnyNIYH5xWb641ZWeZKjQaT1ETSd2pXIY3Y"
  oauth_token_secret = "zaM00kSIcQFGjZ4Nlf5ws2CGzZmgw2y6SNbRP3uJUs"
  

 